/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as Context from "./server/context"





declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenRootTypes {
  AuthPayload: { // root type
    token?: string | null; // String
    user?: NexusGenRootTypes['User'] | null; // User
  }
  Deduction: { // root type
    id?: number | null; // Int
    message?: string | null; // String
    summary?: number | null; // Int
  }
  Mutation: {};
  Product: { // root type
    count?: number | null; // Int
    id?: number | null; // Int
    name?: string | null; // String
    price?: number | null; // Int
  }
  Query: {};
  Sale: { // root type
    count?: number | null; // Int
    createdAt?: string | null; // String
    discount?: number | null; // Int
    id?: number | null; // Int
    note?: string | null; // String
    summary?: number | null; // Int
  }
  Store: { // root type
    id?: number | null; // Int
    name?: string | null; // String
  }
  User: { // root type
    id?: number | null; // Float
    name?: string | null; // String
    role?: string | null; // String
  }
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  String: NexusGenScalars['String'];
  Int: NexusGenScalars['Int'];
  Float: NexusGenScalars['Float'];
  Boolean: NexusGenScalars['Boolean'];
  ID: NexusGenScalars['ID'];
}

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string | null; // String
    user: NexusGenRootTypes['User'] | null; // User
  }
  Deduction: { // field return type
    id: number | null; // Int
    message: string | null; // String
    store: NexusGenRootTypes['Store'] | null; // Store
    summary: number | null; // Int
  }
  Mutation: { // field return type
    addProduct: NexusGenRootTypes['Product'] | null; // Product
    addSale: NexusGenRootTypes['Sale'] | null; // Sale
    login: NexusGenRootTypes['AuthPayload'] | null; // AuthPayload
  }
  Product: { // field return type
    count: number | null; // Int
    id: number | null; // Int
    name: string | null; // String
    price: number | null; // Int
    store: NexusGenRootTypes['Store'] | null; // Store
  }
  Query: { // field return type
    deductions: Array<NexusGenRootTypes['Deduction'] | null> | null; // [Deduction]
    me: NexusGenRootTypes['User'] | null; // User
    products: Array<NexusGenRootTypes['Product'] | null> | null; // [Product]
    sales: Array<NexusGenRootTypes['Sale'] | null> | null; // [Sale]
    stores: Array<NexusGenRootTypes['Store'] | null> | null; // [Store]
    users: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  Sale: { // field return type
    count: number | null; // Int
    createdAt: string | null; // String
    discount: number | null; // Int
    id: number | null; // Int
    note: string | null; // String
    product: NexusGenRootTypes['Product'] | null; // Product
    store: NexusGenRootTypes['Store'] | null; // Store
    summary: number | null; // Int
  }
  Store: { // field return type
    id: number | null; // Int
    name: string | null; // String
    products: Array<NexusGenRootTypes['Product'] | null> | null; // [Product]
    users: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  User: { // field return type
    id: number | null; // Float
    name: string | null; // String
    role: string | null; // String
    stores: Array<NexusGenRootTypes['Store'] | null> | null; // [Store]
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Deduction: { // field return type name
    id: 'Int'
    message: 'String'
    store: 'Store'
    summary: 'Int'
  }
  Mutation: { // field return type name
    addProduct: 'Product'
    addSale: 'Sale'
    login: 'AuthPayload'
  }
  Product: { // field return type name
    count: 'Int'
    id: 'Int'
    name: 'String'
    price: 'Int'
    store: 'Store'
  }
  Query: { // field return type name
    deductions: 'Deduction'
    me: 'User'
    products: 'Product'
    sales: 'Sale'
    stores: 'Store'
    users: 'User'
  }
  Sale: { // field return type name
    count: 'Int'
    createdAt: 'String'
    discount: 'Int'
    id: 'Int'
    note: 'String'
    product: 'Product'
    store: 'Store'
    summary: 'Int'
  }
  Store: { // field return type name
    id: 'Int'
    name: 'String'
    products: 'Product'
    users: 'User'
  }
  User: { // field return type name
    id: 'Float'
    name: 'String'
    role: 'String'
    stores: 'Store'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addProduct: { // args
      count?: number | null; // Int
      name: string; // String!
      price: number; // Int!
      storeId: number; // Int!
    }
    addSale: { // args
      count: number; // Int!
      discount?: number | null; // Int
      note?: string | null; // String
      productId: number; // Int!
      storeId: number; // Int!
    }
    login: { // args
      name: string; // String!
      password: string; // String!
    }
  }
  Query: {
    deductions: { // args
      storeId: number; // Int!
    }
    products: { // args
      storeId: number; // Int!
    }
    sales: { // args
      storeId: number; // Int!
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "AuthPayload" | "Deduction" | "Mutation" | "Product" | "Query" | "Sale" | "Store" | "User";

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}