/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as Context from "./server/context"
import { FieldAuthorizeResolver } from "@nexus/schema/dist/plugins/fieldAuthorizePlugin"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    model: NexusPrisma<TypeName, 'model'>
    crud: any
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
  Role: "ADMIN" | "SELLER"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenRootTypes {
  AuthPayload: { // root type
    token?: string | null; // String
    user?: NexusGenRootTypes['User'] | null; // User
  }
  Deduction: { // root type
    id: number; // Int!
    message: string; // String!
    summary: number; // Int!
  }
  Mutation: {};
  Product: { // root type
    count: number; // Float!
    id: number; // Int!
    name: string; // String!
    price: number; // Int!
  }
  Query: {};
  Sale: { // root type
    count: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    discount: number; // Int!
    id: number; // Int!
    note?: string | null; // String
    summary: number; // Int!
  }
  Store: { // root type
    id: number; // Int!
    name: string; // String!
  }
  User: { // root type
    id: number; // Int!
    name: string; // String!
    role: NexusGenEnums['Role']; // Role!
  }
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  Role: NexusGenEnums['Role'];
  String: NexusGenScalars['String'];
  Int: NexusGenScalars['Int'];
  Float: NexusGenScalars['Float'];
  Boolean: NexusGenScalars['Boolean'];
  ID: NexusGenScalars['ID'];
  DateTime: NexusGenScalars['DateTime'];
}

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string | null; // String
    user: NexusGenRootTypes['User'] | null; // User
  }
  Deduction: { // field return type
    id: number; // Int!
    message: string; // String!
    store: NexusGenRootTypes['Store'] | null; // Store
    summary: number; // Int!
  }
  Mutation: { // field return type
    addProduct: NexusGenRootTypes['Product'] | null; // Product
    addSale: NexusGenRootTypes['Sale'] | null; // Sale
    editProduct: NexusGenRootTypes['Product'] | null; // Product
    login: NexusGenRootTypes['AuthPayload'] | null; // AuthPayload
  }
  Product: { // field return type
    count: number; // Float!
    id: number; // Int!
    name: string; // String!
    price: number; // Int!
    store: NexusGenRootTypes['Store'] | null; // Store
  }
  Query: { // field return type
    deductions: Array<NexusGenRootTypes['Deduction'] | null> | null; // [Deduction]
    me: NexusGenRootTypes['User'] | null; // User
    product: NexusGenRootTypes['Product'] | null; // Product
    products: Array<NexusGenRootTypes['Product'] | null> | null; // [Product]
    sales: Array<NexusGenRootTypes['Sale'] | null> | null; // [Sale]
    stores: Array<NexusGenRootTypes['Store'] | null> | null; // [Store]
  }
  Sale: { // field return type
    count: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    discount: number; // Int!
    id: number; // Int!
    note: string | null; // String
    product: NexusGenRootTypes['Product'] | null; // Product
    store: NexusGenRootTypes['Store'] | null; // Store
    summary: number; // Int!
  }
  Store: { // field return type
    id: number; // Int!
    name: string; // String!
    products: Array<NexusGenRootTypes['Product'] | null> | null; // [Product]
    users: Array<NexusGenRootTypes['User'] | null> | null; // [User]
  }
  User: { // field return type
    id: number; // Int!
    name: string; // String!
    role: NexusGenEnums['Role']; // Role!
    stores: Array<NexusGenRootTypes['Store'] | null> | null; // [Store]
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Deduction: { // field return type name
    id: 'Int'
    message: 'String'
    store: 'Store'
    summary: 'Int'
  }
  Mutation: { // field return type name
    addProduct: 'Product'
    addSale: 'Sale'
    editProduct: 'Product'
    login: 'AuthPayload'
  }
  Product: { // field return type name
    count: 'Float'
    id: 'Int'
    name: 'String'
    price: 'Int'
    store: 'Store'
  }
  Query: { // field return type name
    deductions: 'Deduction'
    me: 'User'
    product: 'Product'
    products: 'Product'
    sales: 'Sale'
    stores: 'Store'
  }
  Sale: { // field return type name
    count: 'Int'
    createdAt: 'DateTime'
    discount: 'Int'
    id: 'Int'
    note: 'String'
    product: 'Product'
    store: 'Store'
    summary: 'Int'
  }
  Store: { // field return type name
    id: 'Int'
    name: 'String'
    products: 'Product'
    users: 'User'
  }
  User: { // field return type name
    id: 'Int'
    name: 'String'
    role: 'Role'
    stores: 'Store'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addProduct: { // args
      count?: number | null; // Int
      name: string; // String!
      price: number; // Int!
      storeId: number; // Int!
    }
    addSale: { // args
      count: number; // Int!
      discount?: number | null; // Int
      note?: string | null; // String
      productId: number; // Int!
      storeId: number; // Int!
    }
    editProduct: { // args
      count?: number | null; // Int
      name?: string | null; // String
      price?: number | null; // Int
      productId: number; // Int!
    }
    login: { // args
      name: string; // String!
      password: string; // String!
    }
  }
  Query: {
    deductions: { // args
      storeId: number; // Int!
    }
    product: { // args
      productId: number; // Int!
    }
    products: { // args
      storeId: number; // Int!
    }
    sales: { // args
      storeId: number; // Int!
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "AuthPayload" | "Deduction" | "Mutation" | "Product" | "Query" | "Sale" | "Store" | "User";

export type NexusGenInputNames = never;

export type NexusGenEnumNames = "Role";

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "DateTime" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Authorization for an individual field. Returning "true"
     * or "Promise<true>" means the field can be accessed.
     * Returning "false" or "Promise<false>" will respond
     * with a "Not Authorized" error for the field.
     * Returning or throwing an error will also prevent the
     * resolver from executing.
     */
    authorize?: FieldAuthorizeResolver<TypeName, FieldName>
  }
  interface NexusGenPluginSchemaConfig {
  }
}